### ISSUE TITLE
add a script for loading in matlab

### ISSUE THREAD

**Issue by freeman-lab** [codeneuro/spikefinder-datasets#2]
We need an `example.m` script to show very basic loading and plotting in Matlab, similar to `example.py`.  @philippberens maybe you can do this one?

**Comment by philippberens** [comment]
@freeman-lab yes, no problem. can you put the data somewhere, so i can test it?

**Comment by philippberens** [comment]
never mind, read the emails in reverse order

**Comment by philippberens** [comment]
this is done see my pull request
